/**
 * Created by Administrator on 2015/9/18.
 */

var i18n = {
	'SYS_ERROR_MESSAGE': '系统错误，我们会尽快修复！',
	'SYS_SUCCESS_MESSAGE': '操作成功！',
	'SYS_SUCCESS_CODE': 0,
	'SYS_ERROR_CODE': 1,
	'SYS_IGNORE_CODE': 2,
	'CODE_UPDATE_PASSWORD_ERROR': 3,
	'USER_LOGIN_INPUT_ERROR': '您输入的用户名或密码格式不正确！',
	'USER_LOGIN_USER_NOT_EXIST': '您输入的账号不存在！',
	'USER_LOGIN_USER_PASSWORD_ERROR': '您输入的密码错误！',
	'USER_UPDATE_OLD_PASSWORD_ERROR': '原始密码不正确',
	'USER_UPDATE_PASSWORD_INPUT_ERROR': '密码格式不正确',
	'USER_UPDATE_NEW_CONFIRM_PASSWORD_DIFFERENT': '新密码和确认密码不一致',
	'ADMIN_USER_EXIST_ERROR': '您填写的用户名已经存在，请重新填写！',
	'ADMIN_PRODUCT_EXIST_ERROR': '产品已存在！',
	'ADMIN_USER_UPDATE_ERROR': '对不起，您更新用户信息失败！',
	'ADMIN_USER_UPDATE_SUCCESS': '您更新用户信息成功！',
	'ADMIN_USER_RESET_PASSWORD_ERROR': '对不起，重置用户密码失败！',
	'ADMIN_USER_RESET_PASSWORD_SUCCESS': '重置用户密码成功！',
	'ADMIN_LOG_TIME_FORMAT_ERROR': '您选择的时间格式不正确！',
	'WECHAT_INFO_NOT_EXISTS': '微信公众号信息不存在',
	'INVALID_PARAMETER': '无效参数',
	'INVALID_IMEI': '无效IMEI',
	'WATCH_IMEI_IMPORT_FILE_NOT_EXISTS': '对不起，您导入的IMEI文件不存在！',
	'WATCH_IMEI_IMPORT_FILE_CONTENT_EMPTY': '对不起，您导入的IMEI文件内容为空！',
	'WATCH_IMEI_IMPORT_FILE_IMEI_FORMAT_ERROR': '对不起，您导入的文件中有IMEI格式错误！',
	'WATCH_IMEI_IMPORT_FILE_IMEI_EXISTS': '对不起，您导入的文件中有IMEI已经存在！',
	'WATCH_IMEI_IMPORT_FILE_SUCCESS': '您已成功导入IMEI号',
	'RESOURCE_SAVE_DATA_ISNULL':'填写的数据不能为空',
    'RESOURCE_SAVE_VERSION_ISINT':'Version必须为数字',
    'RESOURCE_SAVE_SIZE_ISINT':'大小必须为数字'
};

module.exports = i18n;